### ISSUE TITLE
Recrutamento

### ISSUE THREAD

**Issue by LarissaGuder** [claudioscheer/praticaII#21]
## Erros
- [x] Não esta cadastrando
## Observações: 
- Teve que utilizar o inicializar pelo sistema
## Melhorias a serem feitas
- Acessar o cadastro pela url (manual)
- Cadastro de vagas pela url (manual)
- Melhorar usabilidade
- Trabalhe conosco não esta visivel (acessa via url)
- Tirar o botão voltar
- Clicando em cancelar deve voltar pra tela anterior (treinamentos)

**Comment by andersonseibert** [comment]
Correções realizadas!
