### ISSUE TITLE
Folha de pagamento

### ISSUE THREAD

**Issue by LarissaGuder** [claudioscheer/praticaII#32]
## Folha de pagamento
- [x] Padronizar mensagem de erro - tela cadastro de período
- [x] Selecionar dependentes para o cálculo do imposto
- [x] Padronizar ícones tela envelope
- [x] Mudar relatório da folha para puxar dados variáveis e imagem Murphy

**Comment by claudioscheer** [comment]
A folha de pagamento não terá a imagem do Murphy.
